char * script_feuilles=
"[VERTEXFORMAT]\n"
"	XYZ NORMAL TEX0\n"
"[DEFINES]\n"
"	CONST zero;\n"
"	CONST one=1.0,1.0,1.0,1.0;\n"
"	TEXTURE Tex;\n"
"	MATRIX WORLD;\n"
"	MATRIX VIEWPROJ;\n"
"	VECTOR Light;\n"
"	VECTOR Camera;\n"
"	VECTOR Ambient;\n"
"	VECTOR Color;\n"

"[TECHNIQUE]	Model3\n"
"[PASS0]\n"
"	[POSITION]\n"
"		tPos=iPos*4WORLD;\n"
"		N=iNorm*3WORLD;\n"
"		u=normalise(Light);\n"
"		N=normalise(N);\n"
"		oPos=tPos*4VIEWPROJ;\n"
"	[DIFFUSE]\n"
"      u.x=(u|N);\n"
"		u=u.xxxx*Color;\n"
"		u=max(u,zero);\n"
"		u=u+Ambient;\n"
"		u=min(u,one);\n"
"		oDiffuse=u;\n"
"	[MAPPING0]\n"
"		oTexture0.xy=iTexture0.xy;\n"
"   [SHADER] \n"
"        Out = sample(0,Tex0); \n"
"        Out.rgb = Out.rgb * Diffuse.rgb; \n"

"	[RENDER_STATE]\n"
"		ShadeMode				Smooth\n"
"		Blend					False\n"
"		Texture[0]				Tex\n"
"		ZBuffer					True\n"
"		ZBufferWrite			True\n"
"		TextureCoordinate[0]	TexCoo0\n"
"        Mip[0]                    Linear\n"
"        Mag[0]                    Linear\n"
"        Min[0]                    Linear\n"

"		AlphaTest				True\n"
"		AlphaRef				0x80\n"
"		AlphaFunc				Greater\n"

"[END]\n";
