char * script_tronc_blend=
"[VERTEXFORMAT]\n"
"	XYZ NORMAL BLEND TEX0\n"
"[DEFINES]\n"
"	CONST zero;\n"
"	CONST one=1.0,1.0,1.0,1.0;\n"
"	CONST med=0.5,0.5,0.5,0.5;\n"
"	TEXTURE Tex;\n"
"	MATRIX WORLD;\n"
"	MATRIX DISTORT;\n"
"	MATRIX VIEWPROJ;\n"
"	VECTOR Light;\n"
"	VECTOR Ambient;\n"
"	VECTOR Color;\n"
"	VECTOR Camera;\n"

"[TECHNIQUE]	Model3\n"
"[PASS0]\n"
"	[POSITION]\n"
"		tPos=iWeights.xxxx*(iPos*4WORLD) + iWeights.yyyy*(iPos*4DISTORT);\n"
"		N=iWeights.xxxx*(iNorm*3WORLD) + iWeights.yyyy*(iNorm*3DISTORT);\n"
"		u=normalise(Light);\n"
"		N=normalise(N);\n"
"		oPos=tPos*4VIEWPROJ;\n"
"	[DIFFUSE]\n"
"      u.x=(u|N);\n"
"		u=u.xxxx*Color;\n"
"		u=max(u,zero);\n"
"		u=u+Ambient;\n"
"		u=min(u,one);\n"
"		oDiffuse=u;\n"
"	[MAPPING0]\n"
"		oTexture0.xy=iTexture0.xy;\n"	 
"   [SHADER] \n"
"        Out = sample(0,Tex0); \n"
"        Out.rgb = Out.rgb * Diffuse.rgb; \n"

"	[RENDER_STATE]\n"
"		Blend					False\n"
"		Texture[0]				Tex\n"
"		ZBuffer					True\n"
"		ZBufferWrite			True\n"
"        Min[0]                    Linear\n"
"        Min[1]                    Linear\n"
"        Mag[0]                    Linear\n"
"        Mag[1]                    Linear\n"
"        Mip[0]                    Linear\n"
"        Mip[1]                    Linear\n"
"		TextureCoordinate[0]	TexCoo0\n"

"[END]\n";
